In [1]:
import numpy as np
X = np.arange(12).reshape((3,4))
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
Y = np.arange(12).reshape((4,3))

In [5]:
print(np.dot(X,Y))

[[ 42  48  54]
 [114 136 158]
 [186 224 262]]


In [8]:
oneTen = np.ones((1,10))
tenOne = np.ones((10,1))
tenTen = np.ones((10,10))
print(np.arange(30).reshape(3,10).dot(tenOne.dot(oneTen)))
print(np.arange(30).reshape(3,10).dot(tenTen))

[[ 45.  45.  45.  45.  45.  45.  45.  45.  45.  45.]
 [145. 145. 145. 145. 145. 145. 145. 145. 145. 145.]
 [245. 245. 245. 245. 245. 245. 245. 245. 245. 245.]]
[[ 45.  45.  45.  45.  45.  45.  45.  45.  45.  45.]
 [145. 145. 145. 145. 145. 145. 145. 145. 145. 145.]
 [245. 245. 245. 245. 245. 245. 245. 245. 245. 245.]]


In [2]:
print(np.sum(X, axis=0))

[12 15 18 21]
